spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5432/mmdb
        username: postgres
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
flyway:
    baseline-on-migrate: true
    locations: classpath:/migration
    out-of-order: true
    schemas: public
